### PR TITLE
Feature/polishing

### PR DESCRIPTION
**Pull request by petrholik**
Some minor polishing.

### CODE REVIEW

**Comment by JasperGeurtz** [comment]
Thank you! But I don't think these changes are really required?

**Comment by petrholik** [comment]
It makes possible to open in eclipse IDE without errors. And without trying to commit IDE metadata files.
Feel free to not include, I can have it in my forked repo.

**Comment by JasperGeurtz** [comment]
I don't mind changing the gitignore to help Eclipse, but your package declaration "breaks" the CI

**Comment by petrholik** [comment]
Should be fixed now.

**Pull request merged**
