### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by christian-geier**
consistency with repository section
[complete Java n00b here, took me a while to figure this one out]

### CODE REVIEW

**Comment by JasperGeurtz** [comment]
Hi, thank you for the PR!

Most (if not all) Java repository README's have their `maven dependency` section without the surrounding `<dependencies>`, probably because this is implicitly assumed with `<dependency>`  when you are using maven.

Examples [GSON](https://github.com/google/gson#download) and [jOOQ](https://github.com/jOOQ/jOOR#download)

I added the `<repositories>` around `<repository>` because it is not that usual to need external repositories, at least not if you only use standard/big external dependencies.

So I probably won't merge the diff like this, because most Java projects do it the way it currently is. 
But maybe the explanation within the `Usage` section could be improved?

**Comment by JasperGeurtz** [comment]
And looks like the CI is broken again :(

**Comment by christian-geier** [comment]
Hi, thanks for the fast response and thanks for the clarification, I did not know about these conventions; agree a clarification in the usage section would be useful for absolute newcomers like me..

I was following this guide:

[https://github.com/JavaBWAPI/Java-BWAPI-Tutorial/wiki/Setup]

where it simply states:

"Next follow the usage instructions in the JBWAPI Readme to add JBWAPI as a library"

**Comment by JasperGeurtz** [comment]
I've updated the tutorial with a full pom.xml in text (there was already an image, but that might not have been clear enough!).
I also added a small clarification to the README that it should be added as a dependency in the `<dependencies></dependencies>`.

Please let me know if it is more clear now :)

**Comment by christian-geier** [comment]
Cool, I think that's clear and will help. Thanks!

**Pull request closed without merging**
